service: publications-api

provider:
  name: aws
  runtime: nodejs8.10

functions:
  publications:
    handler: src/publications.get
    events:
      - http:
          path: publications
          method: get
          cors: true

  create-publication:
    handler: src/publications.create
    events:
      - http:
          path: publications
          method: post
          cors: true

  authors:
    handler: src/authors.create
    events:
      - http:
          path: authors
          method: post
          cors: true
plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0 # for docker container hosting